### ISSUE TITLE
Not working in Sitecore 8.2

### ISSUE THREAD

**Issue by kerygmafabian** [dresser/SitecoreEzImporter#1]
Hi,
the module seems not to work in SC8.2.,

I installed it and creatred an Import Map. But when I try to import nothing happens, it just hangs on the progress screen.

In console I get the following errors:
GET http://gurit/sitecore/api/ssc/EzImporter-Controllers/Import/1/DefaultSettings  404 (Not Found)
GET http://gurit/api/sitecore/Settings/SetUserProfileKey 400 (Parameters are wrong.)
GET http://gurit/sitecore/api/ssc/EzImporter-Controllers/Import/1/DefaultSettings 404 (Not Found)

Thanks.

**Comment by dresser** [comment]
Hi,
Thanks for trying out my module and sorry for the delay in responding.
Can you tell me which release of Sitecore 8.2 you are using? I tried the sample import map and file and it worked ok on Sitecore 8.2 rev. 161115 (Update 1).
Thanks,
Matt

**Comment by TomaNet** [comment]
Hi, I've had similar issues when I tried it using Sitecore 8.2 rev2 161221 (Update 2) . The import just hangs without any discernable alerts or issues. I've treid it with multiple CSV and XLSX files, small and large.

**Comment by dresser** [comment]
Hi @TomaNet 
Sorry to hear you've been experiencing problems. 

If you open the network tab of the browser developer tools, do you see any failed requests?
If you are able to provide me with your CSV / XLSX and your mapping, I will be happy to investigate the problem.

The installation should add the following files:
\bin\Sitecore.EzImporter.dll
\bin\Excel.dll
\bin\ICSharpCode.SharpZipLib.dll
\App_Config\Include\EzImporter\Sitecore.EzImporter.config
\sitecore\shell\client\Applications\EzImporter\SitecoreEzImporter.js
Could you check that they are present in your Sitecore instance website folder?

Thanks,

Matt

**Comment by dresser** [comment]
@kerygmafabian 
could you check that you have the files mentioned in the above comment in your instance?
Thanks,
Matt

**Comment by rakeshmr22** [comment]
Hi,

I am not able to import the data  from simple excel file. Version of SItecore is 8.2 update 2.
It is keep on progressing.
Below files are present
\bin\Sitecore.EzImporter.dll
\bin\Excel.dll
\bin\ICSharpCode.SharpZipLib.dll
\App_Config\Include\EzImporter\Sitecore.EzImporter.config
\sitecore\shell\client\Applications\EzImporter\SitecoreEzImporter.js
![image](https://user-images.githubusercontent.com/27285188/30736283-b8fd39c4-9f9f-11e7-87a0-6c76a7a61647.png)
please help here.

Please share me the detailed instructions to create Target template, Inputfield, output field , mapping.
It would be nice if you could share me the detailed instructions if I have missed any.
I have also followed the steps given in the link mentioned below.
http://www.matthewdresser.com/sitecore/ez-importer-excel-import-utility

**Comment by rohitgautamhs** [comment]
Hi, I am getting the below error on 8.2 Update 5

**ERROR EzImporter:Invalid Excel file 'Stream is not seekable
Parameter name: stream'**

also getting the below in console
**http://localhost/api/sitecore/Settings/SetUserProfileKey 400 (Parameters are wrong.)**

**Comment by tiwaripk88** [comment]
Same Error for me as well, 'Stream' is not seekable. I am trying this module on 8.2 update 5

**Comment by alejandroschmechel** [comment]
Hey @dresser,
Thanks for developing this solution,

I need a small help, I'm using Sitecore version 8.1 update 3, and installed the package following the steps listed on the Sitecore Marketplace. I also imported the SampleMap and I'm trying to test using the 'Cars' xls file you have there. But when I try to upload it the loader is frozen as the screenshot @rakeshmr22 shared,
here are some screenshot of the screens and the log file:

Screen with request headers:
![screenshot_1](https://user-images.githubusercontent.com/5282094/34682392-f4e8193c-f485-11e7-81ab-f0d19ba116fc.png)
Log file:
![screenshot_2](https://user-images.githubusercontent.com/5282094/34682393-f515b770-f485-11e7-91ab-c75f366c0ba8.png)

Did you experienced something like this? 
Thanks and Best

**Comment by alejandroschmechel** [comment]
Hey Guys,

Just to inform that I was able to resolve this issue,
The problem is that I'm using a multi-language approach, I had the mappers created with only a version in the main language, when I created mapper versions to all languages it worked directly.

Thanks and Best!

**Comment by egbertwietses** [comment]
Same issue Sitecore 8.2 Update 5

When trying to import the test data:
With dotPeek trying to find what goes wrong.

Exception System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij EzImporter.Map.Factory.CreateOutputMap(Item item, OutputMap parentMap)
   bij System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij EzImporter.Map.Factory.BuildMapInfo(ID mapId)
   bij EzImporter.Controllers.ImportController.Import(ImportModel importModel)

**Comment by dresser** [comment]
Hi @alejandroschmechel 

Sorry for the slow response. You are right, this seems to be related to the editor language in Sitecore. I reproduced the issue when I logged in with a new admin account set up for de-DE. Some of the dropdown items in the UI were empty (including their values).

This issue has now been fixed.

Thanks for your feedback,

Matt

**Comment by richardw12** [comment]
I'm getting similar error to the original poster with Sitecore 8.2 update 5.  This appears as soon as I open the EzImporter module, before I click the Import button:

http://mysite.local/sitecore/api/ssc/EzImporter-Controllers/Import/1/DefaultSettings 404 (Not Found)
http://mysite.local/api/sitecore/Settings/SetUserProfileKey 400 (Parameters are wrong.)

All these files are present in my sitecore instance:

\bin\Sitecore.EzImporter.dll
\bin\Excel.dll
\bin\ICSharpCode.SharpZipLib.dll
\App_Config\Include\EzImporter\Sitecore.EzImporter.config
\sitecore\shell\client\Applications\EzImporter\SitecoreEzImporter.js

I have a multilanguage setup, with 7 languages, if that makes any difference.

I originally downloaded the package from the Sitecore marketplace - https://marketplace.sitecore.net/Modules/E/Ez_Importer.aspx which doesn't look like it's been updated for a while.

I tried downloading the latest source code, building it and copying the dll to my sitecore instance, but I still get the same errors.

**Comment by dresser** [comment]
Hi @rw0838 
You can try using Version 1.03 which you can download directly from github here: https://github.com/dresser/SitecoreEzImporter/releases/tag/v1.0.3
