### ISSUE TITLE
Import treelist field type 

### ISSUE THREAD

**Issue by akmalanu** [dresser/SitecoreEzImporter#2]
I have sitecore content that has treelist field type. I try to used ez importer to import it and look for it on documentation, but no luck.
Please advise, is it possible to import treelist field type to sitecore using ez importer and how can I do it.

Thanks.

**Comment by dresser** [comment]
Hi @akmalanu 

Yes, it is possible! You have a few options here. Sitecore stores the selected values of a treelist field as a series of GUIDs - you can see this in the content editor if you select View > Raw Values. Your excel or csv inout file will need to have either

- a list of IDs to import
- a list of item names to import

These can be pipe-separated (the "|" character) or you can use a different separator. This is where you use the "multiple values separator" field in the UI of the tool, in case you need to use a different separator.

If you know the IDs then, you simply provide pipe-separated IDs in your input file. If not, then you can supply the names of the items and it will try to determine their IDs based on the source of the template field.

Hope this helps. If you want to discuss in more detail, its probably easiest to contact me via sitecorechat.slack.com (my username is matthew.dresser).
